/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_szajsjem_jni_BeeDnnLibdll */

#ifndef _Included_pl_szajsjem_jni_BeeDnnLibdll
#define _Included_pl_szajsjem_jni_BeeDnnLibdll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_szajsjem_jni_BeeDnnLibdll
 * Method:    getLayerType
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_pl_szajsjem_jni_BeeDnnLibdll_getLayerType
  (JNIEnv *, jclass);

/*
 * Class:     pl_szajsjem_jni_BeeDnnLibdll
 * Method:    getActivationFunctions
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_pl_szajsjem_jni_BeeDnnLibdll_getActivationFunctions
  (JNIEnv *, jclass);

/*
 * Class:     pl_szajsjem_jni_BeeDnnLibdll
 * Method:    getInitializers
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_pl_szajsjem_jni_BeeDnnLibdll_getInitializers
  (JNIEnv *, jclass);

/*
 * Class:     pl_szajsjem_jni_BeeDnnLibdll
 * Method:    getOptimizers
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_pl_szajsjem_jni_BeeDnnLibdll_getOptimizers
  (JNIEnv *, jclass);

/*
 * Class:     pl_szajsjem_jni_BeeDnnLibdll
 * Method:    getLossFunctions
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_pl_szajsjem_jni_BeeDnnLibdll_getLossFunctions
  (JNIEnv *, jclass);

/*
 * Class:     pl_szajsjem_jni_BeeDnnLibdll
 * Method:    getRegularizers
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_pl_szajsjem_jni_BeeDnnLibdll_getRegularizers
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
